[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100
src_paths = ["nyx"]

[tool.ruff]
line-length = 100
target-version = "py311"
extend-select = [
  "E", "F", "I",         # pycodestyle/pyflakes/imports
  "UP",                  # pyupgrade
  "B",                   # bugbear
  "SIM",                 # flake8-simplify
  "PIE",                 # flake8-pie
  "Q",                   # flake8-quotes
]
ignore = [
  "E203", "E501"         # handled by black / line length OK
]
fix = true
exclude = ["**/__pycache__", "runtime/**"]

[tool.mypy]
python_version = "3.11"
warn_unused_ignores = true
ignore_missing_imports = true
strict_optional = false
namespace_packages = true
no_site_packages = false
