
version: 1

defaults:
  # global caps (fallbacks if a profile doesn't define)
  max_spread_pct: 2.0
  max_slippage_bps: 250
  min_depth_sol: 30
  tax_max_bps: 600
  lp_locked_required: false
  probe_sol: 0.02
  max_sol: 0.25
  early_window:
    seconds: 120
    probe_relief: -10    # lower probe threshold by 10 pts during early window
  trusted_source_relief: -5
  bundle_penalty: +10

snipe:
  t0_liquidity:
    when:
      max_pool_age_s: 120
      max_token_age_s: 600
    gates:
      lp_locked_required: true
      min_lp_sol: 50
      tax_max_bps: 400
      max_spread_pct: 1.5
      max_slippage_bps: 200
      min_depth_sol: 50
      honeypot: false
    weights:
      onchain: 5
      flow: 3
      social: 2
      chart: 1
      memory: 1
    thresholds:
      # legacy
      probe: 60
      buy: 75
      watch_hold: 45
      exit: 35
      # band-style
      ignore_max: 22         # tighter watcher
      watch_max:  48
      buy_min:    48         # hard lower bound for BUY band (overrides relief)
      buy_max:    72
      agg_max:    88
      probe_split: 0.40      # lower 40% of BUY band becomes "probe"
      buy_relief: 2.0        # extra easing if buy_min not set
    dynamic:
      early_window:
        seconds: 120
        probe_relief: -10
      trusted_source_relief: -5
      bundle_penalty: +10
    sizing:
      probe_sol: 0.02
      max_sol: 0.10
      scale_plan: [0.4, 0.3, 0.3]
      stop_model: structure
      trail:
        ema: 9

  breakout:
    when:
      min_bars_1m: 5
    gates:
      max_spread_pct: 1.2
      max_slippage_bps: 180
      min_depth_sol: 40
      honeypot: false
    weights:
      chart: 4
      flow: 3
      onchain: 2
      social: 1
      memory: 1
    thresholds:
      # legacy
      probe: 60
      buy: 78
      watch_hold: 50
      exit: 40
      # band-style
      ignore_max: 24
      watch_max:  50
      buy_min:    52        # breakout waits for a bit more confirmation
      buy_max:    76
      agg_max:    88
      probe_split: 0.35
      buy_relief: 1.5
    dynamic:
      early_window:
        seconds: 180
        probe_relief: -5
    sizing:
      probe_sol: 0.03
      max_sol: 0.15
      scale_plan: [0.33, 0.33, 0.34]
      stop_model: structure
      trail:
        ema: 12

  social_react:
    when:
      trusted_source_ping: true
    gates:
      honeypot: false
      max_spread_pct: 1.8
      max_slippage_bps: 220
      min_depth_sol: 30
      tax_max_bps: 600
    weights:
      social: 4
      onchain: 3
      flow: 2
      chart: 1
      memory: 1
    thresholds:
      # legacy
      probe: 58
      buy: 76
      watch_hold: 48
      exit: 38
      # band-style
      ignore_max: 24
      watch_max:  48
      buy_min:    48        # reacts fast on trusted ping
      buy_max:    72
      agg_max:    88
      probe_split: 0.40
      buy_relief: 3.0       # trusted pings can ease buy entry
    dynamic:
      trusted_source_relief: -8
    sizing:
      probe_sol: 0.02
      max_sol: 0.12
      scale_plan: [0.5, 0.25, 0.25]
      stop_model: structure
      trail:
        ema: 9

  anti_mev:
    when:
      bundle_risk: true
    gates:
      confirm_blocks_if_bundle: 1
      max_spread_pct: 1.2
      max_slippage_bps: 150
      min_depth_sol: 60
      honeypot: false
    weights:
      flow: 4
      onchain: 3
      memory: 2
      chart: 1
      social: 0.5
    thresholds:
      # legacy
      probe: 62
      buy: 80
      watch_hold: 52
      exit: 42
      # band-style
      ignore_max: 24
      watch_max:  52
      buy_min:    54        # stricter entry under bundle risk
      buy_max:    78
      agg_max:    90
      probe_split: 0.30
      buy_relief: 1.0
    dynamic:
      bundle_penalty: +10
    sizing:
      probe_sol: 0.015
      max_sol: 0.08
      scale_plan: [0.4, 0.3, 0.3]
      stop_model: structure
      trail:
        ema: 9

trade:
  momentum:
    gates:
      lp_locked_required: false
      max_spread_pct: 2.0
      max_slippage_bps: 250
      min_depth_sol: 30
      honeypot: false
    weights:
      chart: 4
      onchain: 3
      memory: 2
      social: 1
      flow: 0.5
    thresholds:
      # legacy
      probe: 60
      buy: 70
      watch_hold: 50
      exit: 35
      # band-style
      ignore_max: 24
      watch_max:  50
      buy_min:    50
      buy_max:    68
      agg_max:    85
      probe_split: 0.40
      buy_relief: 0.0
    sizing:
      probe_sol: 0.03
      max_sol: 0.30
      scale_plan: [0.33, 0.33, 0.34]
      stop_model: atr
      trail:
        atr_mult: 2.0

  pullback:
    gates:
      max_spread_pct: 2.0
      max_slippage_bps: 250
      min_depth_sol: 30
      honeypot: false
    weights:
      chart: 4
      memory: 2
      onchain: 2
      social: 1
      flow: 0.5
    thresholds:
      # legacy
      probe: 58
      buy: 68
      watch_hold: 48
      exit: 35
      # band-style
      ignore_max: 24
      watch_max:  48
      buy_min:    48
      buy_max:    66
      agg_max:    84
      probe_split: 0.35
      buy_relief: 0.0
    sizing:
      probe_sol: 0.03
      max_sol: 0.30
      add_on_reclaim: true
      stop_model: structure
      trail:
        ema: 20

  mean_reversion:
    gates:
      avoid_trend_if_trend_score_gt: 0.7
      max_spread_pct: 2.2
      max_slippage_bps: 280
      min_depth_sol: 25
      honeypot: false
    weights:
      chart: 3.5     # BB/VWAP/distance
      memory: 2
      onchain: 2
      social: 0.5
      flow: 0.5
    thresholds:
      # legacy
      probe: 55
      buy: 66
      watch_hold: 46
      exit: 34
      # band-style
      ignore_max: 24
      watch_max:  46
      buy_min:    46
      buy_max:    64
      agg_max:    82
      probe_split: 0.35
      buy_relief: 0.0
    sizing:
      probe_sol: 0.03
      max_sol: 0.25
      stop_model: atr
      trail:
        atr_mult: 1.5

  news_theme:
    gates:
      honeypot: false
      max_spread_pct: 2.2
      max_slippage_bps: 280
      min_depth_sol: 25
    weights:
      social: 3.5
      memory: 3
      chart: 2
      onchain: 1.5
      flow: 0.5
    thresholds:
      # legacy
      probe: 58
      buy: 70
      watch_hold: 48
      exit: 36
      # band-style
      ignore_max: 24
      watch_max:  48
      buy_min:    48
      buy_max:    68
      agg_max:    86
      probe_split: 0.35
      buy_relief: 0.0
    sizing:
      probe_sol: 0.03
      max_sol: 0.28
      stop_model: atr
      trail:
        atr_mult: 2.0
